defaults:
  - machine: A6000.yaml

do_train: true
do_eval: true
output_dir: ${hydra:run.dir}
logging_steps: 2
num_epochs: 10
learning_rate: 3e-4
warmup_steps: 0
save_steps: 10
eval_steps: 10
save_total_limit: 1
seed: 777
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 4
evaluation_strategy: steps
do_grad_norm_clip: true
max_grad_norm: 1.0
log_with: mlflow
project_name: "default"
run_name: "run_${now:%Y-%m-%d}"
checkpoint_save_limit: 3